"""add guesses table

Revision ID: d83a8c931e3c
Revises: a179ad8e340d
Create Date: 2026-08-23 23:33:07.306569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83a8c931e3c'
down_revision: Union[str, Sequence[str], None] = 'a179ad8e340d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_answer_id', sa.Integer(), nullable=False),
    sa.Column('guessed_card_id', sa.Integer(), nullable=False),
    sa.Column('guest_session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_answer_id'], ['daily_answers.id'], ),
    sa.ForeignKeyConstraint(['guessed_card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guesses_daily_answer_id'), 'guesses', ['daily_answer_id'], unique=False)
    op.create_index(op.f('ix_guesses_guest_session_id'), 'guesses', ['guest_session_id'], unique=False)
    op.create_index(op.f('ix_guesses_id'), 'guesses', ['id'], unique=False)
    op.create_index(op.f('ix_guesses_user_id'), 'guesses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guesses_user_id'), table_name='guesses')
    op.drop_index(op.f('ix_guesses_id'), table_name='guesses')
    op.drop_index(op.f('ix_guesses_guest_session_id'), table_name='guesses')
    op.drop_index(op.f('ix_guesses_daily_answer_id'), table_name='guesses')
    op.drop_table('guesses')
    # ### end Alembic commands ###
